# data lists
TRADES = [
 ("HVAC Contractors","HVAC contractors","238220","hvac-contractors"),
 ("Electrical Contractors","electrical contractors","238210","electrical-contractors"),
 ("Plumbing Contractors","plumbing contractors","238220","plumbing-contractors"),
 ("Painting Contractors","painting contractors","238320","painting-contractors"),
 ("Roofing Contractors","roofing contractors","238160","roofing-contractors"),
 ("Concrete Contractors","concrete contractors","238110","concrete-contractors"),
 ("Masonry Contractors","masonry contractors","238140","masonry-contractors"),
 ("Flooring Contractors","flooring contractors","238330","flooring-contractors"),
 ("Glass & Glazing Contractors","glass and glazing contractors","238150","glass-glazing-contractors"),
 ("Drywall Contractors","drywall contractors","238310","drywall-contractors"),
 ("Framing Contractors","framing contractors","238130","framing-contractors"),
 ("Excavation Contractors","excavation contractors","238910","excavation-contractors"),
 ("Fencing Contractors","fencing contractors","238990","fencing-contractors"),
 ("Elevator Contractors","elevator contractors","238290","elevator-contractors"),
 ("Landscaping Services","landscaping services","561730","landscaping-services"),
 ("Janitorial Services","janitorial services","561720","janitorial-services"),
 ("Pest Control Services","pest control services","561710","pest-control-services"),
 ("Security Guard Services","security guard services","561612","security-guard-services"),
 ("Security System Installers","security system installers","561621","security-system-installers"),
 ("Waste Collection Services","waste collection services","562111","waste-collection-services"),
 ("General Building Contractors","general building contractors","236220","general-building-contractors"),
 ("Highway & Road Construction","highway and road construction","237310","highway-road-construction"),
 ("Water & Sewer Construction","water and sewer construction","237110","water-sewer-construction"),
 ("Power Line Construction","power line construction","237130","power-line-construction"),
 ("IT Services","IT services","541512","it-services"),
 ("Software Developers","software developers","541511","software-developers"),
 ("Management Consultants","management consultants","541611","management-consultants"),
 ("Engineering Services","engineering services","541330","engineering-services"),
 ("Architectural Services","architectural services","541310","architectural-services"),
 ("Accounting Services","accounting services","541211","accounting-services"),
 ("Environmental Consultants","environmental consultants","541620","environmental-consultants"),
 ("Staffing Agencies","staffing agencies","561320","staffing-agencies"),
 ("Freight Trucking","freight trucking","484110","freight-trucking"),
 ("Facilities Support Services","facilities support services","561210","facilities-support-services"),
 ("Catering & Food Service","catering and food service","722310","catering-food-service"),
 ("Medical Equipment Suppliers","medical equipment suppliers","339112","medical-equipment-suppliers"),
 ("Office Supply Vendors","office supply vendors","453210","office-supply-vendors"),
 ("Signage Contractors","signage contractors","339950","signage-contractors"),
 ("Locksmith Services","locksmith services","561622","locksmith-services"),
 ("Vehicle Maintenance Services","vehicle maintenance services","811111","vehicle-maintenance-services"),
]

STATES = [
 ("Alabama","AL","alabama"),("Alaska","AK","alaska"),("Arizona","AZ","arizona"),("Arkansas","AR","arkansas"),
 ("California","CA","california"),("Colorado","CO","colorado"),("Connecticut","CT","connecticut"),("Delaware","DE","delaware"),
 ("Florida","FL","florida"),("Georgia","GA","georgia"),("Hawaii","HI","hawaii"),("Idaho","ID","idaho"),
 ("Illinois","IL","illinois"),("Indiana","IN","indiana"),("Iowa","IA","iowa"),("Kansas","KS","kansas"),
 ("Kentucky","KY","kentucky"),("Louisiana","LA","louisiana"),("Maine","ME","maine"),("Maryland","MD","maryland"),
 ("Massachusetts","MA","massachusetts"),("Michigan","MI","michigan"),("Minnesota","MN","minnesota"),("Mississippi","MS","mississippi"),
 ("Missouri","MO","missouri"),("Montana","MT","montana"),("Nebraska","NE","nebraska"),("Nevada","NV","nevada"),
 ("New Hampshire","NH","new-hampshire"),("New Jersey","NJ","new-jersey"),("New Mexico","NM","new-mexico"),("New York","NY","new-york"),
 ("North Carolina","NC","north-carolina"),("North Dakota","ND","north-dakota"),("Ohio","OH","ohio"),("Oklahoma","OK","oklahoma"),
 ("Oregon","OR","oregon"),("Pennsylvania","PA","pennsylvania"),("Rhode Island","RI","rhode-island"),("South Carolina","SC","south-carolina"),
 ("South Dakota","SD","south-dakota"),("Tennessee","TN","tennessee"),("Texas","TX","texas"),("Utah","UT","utah"),
 ("Vermont","VT","vermont"),("Virginia","VA","virginia"),("Washington","WA","washington"),("West Virginia","WV","west-virginia"),
 ("Wisconsin","WI","wisconsin"),("Wyoming","WY","wyoming"),
]

STATE_PORTALS = {
 "TX":("Texas SmartBuy / ESBD","https://www.txsmartbuy.gov/esbd"),
 "CA":("Cal eProcure","https://caleprocure.ca.gov/"),
 "FL":("MyFloridaMarketPlace","https://www.myfloridamarketplace.com/"),
 "NY":("New York State Contract Reporter","https://www.nyscr.ny.gov/"),
 "IL":("Illinois Procurement Bulletin","https://www2.illinois.gov/cms/business/sell2/"),
}
